version: "3.8"
networks:
  pageweb:
  based:
 
services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: base_redes
    networks:
      - based
    ports:
      - "3306:3306"
    volumes:
      - pag_mysql_data:/var/lib/mysql
 
  pagina:
    build: .
    container_name: pageweb
    restart: always
    ports:
      - "8080:80"
    networks:
      - pageweb
      - based
    depends_on:
      - mysql_db
    volumes:
      - .:/var/www/html
 
volumes:
  mysql_data: